language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_d7525c7ee7e2_key -iv $encrypted_d7525c7ee7e2_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
